CREATE DATABASE IF NOT EXISTS CRICKET_LEAGUE;

USE CRICKET_LEAGUE;

CREATE TABLE IF NOT EXISTS TEAMS(
TEAM_ID INT AUTO_INCREMENT PRIMARY KEY,
TEAM_NAME VARCHAR(50) UNIQUE NOT NULL,
COUNTRY VARCHAR(100) NOT NULL,
COACH_NAME VARCHAR(50) NOT NULL,
TOTAL_WINS INT DEFAULT 0
);

INSERT INTO TEAMS(TEAM_NAME,COUNTRY,COACH_NAME,TOTAL_WINS) VALUES
('MUMBAI WARRIORS','INDIA','RAHUL SHARMA',2),
('DELHI STRIKERS','INDIA','ANIL KAPOOR',2),
('CHENNAI TITANS','INDIA','VIJAY KUMAR',2),
('SYDNEY SIXERS','AUSTRALIA','JOHN MILLER',0),
('LONDON ROYALS','ENGLAND','DAVID SMITH',1);

SELECT * FROM TEAMS;