CREATE DATABASE COMPANY_TRACKER;
USE COMPANY_TRACKER;

CREATE TABLE DEPARTMENTS(
DEPT_ID INT AUTO_INCREMENT PRIMARY KEY,
DEPT_NAME VARCHAR(100) NOT NULL,
LOCATION VARCHAR(100) NOT NULL,
TOTAL_PROJECTS INT DEFAULT 0
);

INSERT INTO DEPARTMENTS(DEPT_NAME , LOCATION , TOTAL_PROJECTS) VALUES
('ENGINEERING','BANGALORE',3),
('MARKETING','MUMBAI',1),
('SALES','DELHI',1),
('HR','PUNE',1);

SELECT * FROM DEPARTMENTS;