USE STUDENT_GRADES;

CREATE TABLE COURSES(
C_ID INT AUTO_INCREMENT PRIMARY KEY,
C_NAME VARCHAR(50) NOT NULL,
DEPT VARCHAR(50) NOT NULL,
CREDITS INT NOT NULL CHECK(CREDITS>0),
T_ID INT,
FOREIGN KEY(T_ID) REFERENCES TEACHERS(T_ID)
);

INSERT INTO COURSES (C_NAME , DEPT , CREDITS , T_ID) VALUES
('CALCULUS I','MATHEMATICS',4,1),
('LINEAR ALGEBRA','MATHEMATICS',3,1),
('PHYSICS I','PHYSICS',4,2),
('PHYSICS II','PHYSICS',4,2),
('DATA STRUCTURES','COMPUTER SCIENCE',4,3),
('ALGORITHMS','COMPUTER SCIENCE',4,3),
('ORGANIC CHEMISTRY','CHEMISTRY',3,4),
('ENGLISH LITERATURE','ENGLISH',3,5),
('DATABASE SYSTEMS','COMPUTER SCIENCE',3,6),
('CREATIVE WRITING','ENGLISH',2,5);

SELECT * FROM COURSES;