CREATE DATABASE STUDENT_GRADES;
USE STUDENT_GRADES;
 
 CREATE TABLE TEACHERS(
 T_ID INT AUTO_INCREMENT PRIMARY KEY,
 T_NAME VARCHAR(50) NOT NULL,
 DEPT VARCHAR(50) NOT NULL,  
 HIRE_DATE DATE NOT NULL
 );
 
 INSERT INTO TEACHERS(T_NAME , DEPT , HIRE_DATE) VALUES
('DR. ANIL KAPOOR', 'MATHEMATICS', '2015-06-01'),
('DR. SUNITA RAO', 'PHYSICS', '2017-08-15'),
('PROF. RAMESH IYER', 'COMPUTER SCIENCE', '2012-01-10'),
('DR. MEENA JOSHI', 'CHEMISTRY', '2019-03-20'),
('PROF. VIKAS SHARMA', 'ENGLISH', '2016-07-01'),
('DR. KAVITA NAIR', 'COMPUTER SCIENCE', '2020-09-01'),
('DR. ALOK VERMA', 'BIOLOGY', '2021-01-05');

SELECT * FROM TEACHERS;